version: '3'

services:
  web-recipes:
    image: 334687143702.dkr.ecr.ap-southeast-1.amazonaws.com/$CI_PROJECT_NAME:$IMAGE_TAG
    environment:
      SECRET_KEY: $SECRET_KEY
      FLASK_CONFIG: $FLASK_CONFIG
      DATABASE_URL: $DATABASE_URL
    command: >
      sh -c "python manage.py db init &&
             python manage.py db migrate &&
             python manage.py db upgrade &&
             python manage.py runserver"
    ports:
      - "5000:5000"
    networks:
      - recipes

networks: 
    recipes:
      driver: bridge