version: '3'

services:
  web-recipes:
    image: 334687143702.dkr.ecr.ap-southeast-1.amazonaws.com/$CI_PROJECT_NAME:$IMAGE_TAG
    environment:
      SECRET_KEY: "<a random character string>"
      FLASK_CONFIG: "development"
      DATABASE_URL: postgresql://postgres:postgres@172.17.0.2:5432/recipe_db
    command: >
      sh -c "python manage.py db init &&
             python manage.py db migrate &&
             python manage.py db upgrade &&
             python manage.py runserver"
    ports:
      - "5000:5000"
    networks:
      - recipes

networks: 
    recipes:
      driver: bridge